# cookies_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CookiesApi
  # Utility class for custom query_parameter authorization.
  class CustomQueryAuth
    # Add custom authentication to the request.
    # @param [HttpRequest] The HttpRequest object to which authentication will
    # be added.
    def self.apply(config, http_request)
      http_request.add_query_parameter('apikey', config.apikey)
    end
  end
end
