# cookies_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CookiesApi
  # Specifies a list of resulting Brand records.
  class BrandList < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Array of resulting brand records.
    # @return [List of BrandSpec]
    attr_accessor :brand

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['brand'] = 'brand'
      @_hash
    end

    # An array for optional fields
    def optionals
      []
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(brand = nil)
      @brand = brand unless brand == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      brand = nil
      unless hash['brand'].nil?
        brand = []
        hash['brand'].each do |structure|
          brand << (BrandSpec.from_hash(structure) if structure)
        end
      end

      brand = SKIP unless hash.key?('brand')

      # Create object from extracted values.
      BrandList.new(brand)
    end
  end
end
