# cookies_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CookiesApi
  # Asset linked to a managed brand.
  class BrandAsset < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Rasterized asset.
    # @return [RasterGraphic]
    attr_accessor :raster

    # Vector asset, if available.
    # @return [MediaItem]
    attr_accessor :vector

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['raster'] = 'raster'
      @_hash['vector'] = 'vector'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        raster
        vector
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(raster = nil,
                   vector = nil)
      @raster = raster unless raster == SKIP
      @vector = vector unless vector == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      raster = RasterGraphic.from_hash(hash['raster']) if hash['raster']
      vector = MediaItem.from_hash(hash['vector']) if hash['vector']

      # Create object from extracted values.
      BrandAsset.new(raster,
                     vector)
    end
  end
end
