# cookies_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CookiesApi
  # Contact information.
  class Contact < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Phone number.
    # @return [Phone]
    attr_accessor :phone

    # Assigned email domain.
    # @return [String]
    attr_accessor :domain

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['phone'] = 'phone'
      @_hash['domain'] = 'domain'
      @_hash
    end

    # An array for optional fields
    def optionals
      []
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(phone = nil,
                   domain = nil)
      @phone = phone unless phone == SKIP
      @domain = domain unless domain == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      phone = Phone.from_hash(hash['phone']) if hash['phone']
      domain = hash.key?('domain') ? hash['domain'] : SKIP

      # Create object from extracted values.
      Contact.new(phone,
                  domain)
    end
  end
end
