# cookies_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CookiesApi
  # Specifies 1st-party store brands.
  class CookiesBrandEnum
    COOKIES_BRAND_ENUM = [
      # Specifies the brand "Cookies".
      COOKIES = 'COOKIES'.freeze,

      # Specifies the brand "Lemonnade".
      LEMONNADE = 'LEMONNADE'.freeze
    ].freeze
  end
end
