# cookies_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CookiesApi
  # Information describing an error that occurred while transacting with the
  # API.
  class ErrorInfo < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Describes the error with a readable label or message.
    # @return [String]
    attr_accessor :faultstring

    # Further info about the error.
    # @return [ErrorDetail]
    attr_accessor :detail

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['faultstring'] = 'faultstring'
      @_hash['detail'] = 'detail'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        detail
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(faultstring = nil,
                   detail = nil)
      @faultstring = faultstring unless faultstring == SKIP
      @detail = detail unless detail == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      faultstring = hash.key?('faultstring') ? hash['faultstring'] : SKIP
      detail = ErrorDetail.from_hash(hash['detail']) if hash['detail']

      # Create object from extracted values.
      ErrorInfo.new(faultstring,
                    detail)
    end
  end
end
