# cookies_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CookiesApi
  # Detailed information about an error.
  class ErrorDetail < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Specifies an error code or well-qualified error path.
    # @return [String]
    attr_accessor :errorcode

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['errorcode'] = 'errorcode'
      @_hash
    end

    # An array for optional fields
    def optionals
      []
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(errorcode = nil)
      @errorcode = errorcode unless errorcode == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      errorcode = hash.key?('errorcode') ? hash['errorcode'] : SKIP

      # Create object from extracted values.
      ErrorDetail.new(errorcode)
    end
  end
end
