# cookies_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CookiesApi
  # Geo point or boundary information.
  class Geo < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Latitude value for a geo point.
    # @return [Float]
    attr_accessor :latitude

    # Longitude value for a geo point.
    # @return [Float]
    attr_accessor :longitude

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['latitude'] = 'latitude'
      @_hash['longitude'] = 'longitude'
      @_hash
    end

    # An array for optional fields
    def optionals
      []
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(latitude = nil,
                   longitude = nil)
      @latitude = latitude unless latitude == SKIP
      @longitude = longitude unless longitude == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      latitude = hash.key?('latitude') ? hash['latitude'] : SKIP
      longitude = hash.key?('longitude') ? hash['longitude'] : SKIP

      # Create object from extracted values.
      Geo.new(latitude,
              longitude)
    end
  end
end
