# cookies_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CookiesApi
  # Describes regular and special store hours.
  class Hours < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Specifies regular store hours.
    # @return [List of RegularHours]
    attr_accessor :regular

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['regular'] = 'regular'
      @_hash
    end

    # An array for optional fields
    def optionals
      []
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(regular = nil)
      @regular = regular unless regular == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      regular = nil
      unless hash['regular'].nil?
        regular = []
        hash['regular'].each do |structure|
          regular << (RegularHours.from_hash(structure) if structure)
        end
      end

      regular = SKIP unless hash.key?('regular')

      # Create object from extracted values.
      Hours.new(regular)
    end
  end
end
