# cookies_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CookiesApi
  # Describes physical location info.
  class Location < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Street address.
    # @return [Address]
    attr_accessor :address

    # Geo point or boundary.
    # @return [Geo]
    attr_accessor :geo

    # Geo hash.
    # @return [String]
    attr_accessor :hash

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['address'] = 'address'
      @_hash['geo'] = 'geo'
      @_hash['hash'] = 'hash'
      @_hash
    end

    # An array for optional fields
    def optionals
      []
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(address = nil,
                   geo = nil,
                   hash = nil)
      @address = address unless address == SKIP
      @geo = geo unless geo == SKIP
      @hash = hash unless hash == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      address = Address.from_hash(hash['address']) if hash['address']
      geo = Geo.from_hash(hash['geo']) if hash['geo']
      hash = hash.key?('hash') ? hash['hash'] : SKIP

      # Create object from extracted values.
      Location.new(address,
                   geo,
                   hash)
    end
  end
end
