# cookies_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CookiesApi
  # Specifies type information for a media asset.
  class MediaType < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Specifies an image format, as applicable.
    # @return [String]
    attr_accessor :image_type

    # Specifies the broad "kind" of media.
    # @return [String]
    attr_accessor :kind

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['image_type'] = 'imageType'
      @_hash['kind'] = 'kind'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        kind
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(image_type = nil,
                   kind = nil)
      @image_type = image_type unless image_type == SKIP
      @kind = kind unless kind == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      image_type = hash.key?('imageType') ? hash['imageType'] : SKIP
      kind = hash.key?('kind') ? hash['kind'] : SKIP

      # Create object from extracted values.
      MediaType.new(image_type,
                    kind)
    end
  end
end
