# cookies_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CookiesApi
  # Specifies phone-based contact information.
  class Phone < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # E164-formatted phone number.
    # @return [String]
    attr_accessor :e164

    # National display format for the number.
    # @return [String]
    attr_accessor :display

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['e164'] = 'e164'
      @_hash['display'] = 'display'
      @_hash
    end

    # An array for optional fields
    def optionals
      []
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(e164 = nil,
                   display = nil)
      @e164 = e164 unless e164 == SKIP
      @display = display unless display == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      e164 = hash.key?('e164') ? hash['e164'] : SKIP
      display = hash.key?('display') ? hash['display'] : SKIP

      # Create object from extracted values.
      Phone.new(e164,
                display)
    end
  end
end
