# cookies_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CookiesApi
  # Describes a rasterized asset which may carry variants with enhanced
  # resolution.
  class RasterGraphic < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Standard-size graphic asset.
    # @return [MediaItem]
    attr_accessor :standard

    # Retina-size graphic asset.
    # @return [MediaItem]
    attr_accessor :retina

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['standard'] = 'standard'
      @_hash['retina'] = 'retina'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        standard
        retina
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(standard = nil,
                   retina = nil)
      @standard = standard unless standard == SKIP
      @retina = retina unless retina == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      standard = MediaItem.from_hash(hash['standard']) if hash['standard']
      retina = MediaItem.from_hash(hash['retina']) if hash['retina']

      # Create object from extracted values.
      RasterGraphic.new(standard,
                        retina)
    end
  end
end
