# cookies_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CookiesApi
  # Describes regular store hours.
  class RegularHours < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Days which a given regular hours rule applies to.
    # @return [List of String]
    attr_accessor :day

    # Hours to apply on the specified days.
    # @return [List of HoursRange]
    attr_accessor :hours

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['day'] = 'day'
      @_hash['hours'] = 'hours'
      @_hash
    end

    # An array for optional fields
    def optionals
      []
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(day = nil,
                   hours = nil)
      @day = day unless day == SKIP
      @hours = hours unless hours == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      day = hash.key?('day') ? hash['day'] : SKIP
      # Parameter is an array, so we need to iterate through it
      hours = nil
      unless hash['hours'].nil?
        hours = []
        hash['hours'].each do |structure|
          hours << (HoursRange.from_hash(structure) if structure)
        end
      end

      hours = SKIP unless hash.key?('hours')

      # Create object from extracted values.
      RegularHours.new(day,
                       hours)
    end
  end
end
