# cookies_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CookiesApi
  # Describes a rasterized responsive graphic asset.
  class ResponsiveGraphic < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Portrait-style asset.
    # @return [MediaItem]
    attr_accessor :portrait

    # Landscape-style asset.
    # @return [MediaItem]
    attr_accessor :landscape

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['portrait'] = 'portrait'
      @_hash['landscape'] = 'landscape'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        portrait
        landscape
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(portrait = nil,
                   landscape = nil)
      @portrait = portrait unless portrait == SKIP
      @landscape = landscape unless landscape == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      portrait = MediaItem.from_hash(hash['portrait']) if hash['portrait']
      landscape = MediaItem.from_hash(hash['landscape']) if hash['landscape']

      # Create object from extracted values.
      ResponsiveGraphic.new(portrait,
                            landscape)
    end
  end
end
