# cookies_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CookiesApi
  # Social media account property.
  class SocialProperty < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Social network where this profile exists.
    # @return [String]
    attr_accessor :property

    # Link to this social profile.
    # @return [String]
    attr_accessor :link

    # Unique ID for this social profile, or username.
    # @return [String]
    attr_accessor :id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['property'] = 'property'
      @_hash['link'] = 'link'
      @_hash['id'] = 'id'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        link
        id
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(property = nil,
                   link = nil,
                   id = nil)
      @property = property unless property == SKIP
      @link = link unless link == SKIP
      @id = id unless id == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      property = hash.key?('property') ? hash['property'] : SKIP
      link = hash.key?('link') ? hash['link'] : SKIP
      id = hash.key?('id') ? hash['id'] : SKIP

      # Create object from extracted values.
      SocialProperty.new(property,
                         link,
                         id)
    end
  end
end
