# cookies_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CookiesApi
  # Specifies the current status of a store or D2C property.
  class StoreStatusEnum
    STORE_STATUS_ENUM = [
      # The store or property is open for business.
      OPEN = 'OPEN'.freeze,

      # The store or property is closed for business.
      CLOSED = 'CLOSED'.freeze,

      # The store or property is open for pickup only.
      PICKUP_ONLY = 'PICKUP_ONLY'.freeze,

      # The store or property is open for delivery only.
      DELIVERY_ONLY = 'DELIVERY_ONLY'.freeze
    ].freeze
  end
end
