# cookies_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CookiesApi
  # Enumerates available store capabilities.
  class StoreCapabilityEnum
    STORE_CAPABILITY_ENUM = [
      # Pickup ordering.
      PICKUP = 'PICKUP'.freeze,

      # Delivery ordering.
      DELIVERY = 'DELIVERY'.freeze,

      # Curbside pickup ordering.
      CURBSIDE = 'CURBSIDE'.freeze,

      # Globally-enrolled loyalty.
      LOYALTY = 'LOYALTY'.freeze,

      # Accepts debit cards.
      DEBIT = 'DEBIT'.freeze,

      # Licensed for medical sales.
      MEDICAL = 'MEDICAL'.freeze,

      # Licensed for adult-use sales.
      ADULT_USE = 'ADULT_USE'.freeze
    ].freeze
  end
end
