# cookies_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CookiesApi
  # Describes order submission and menu information for a given Cookies store.
  class StoreOrdering < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Ordering platform in use by a Cookies store.
    # @return [String]
    attr_accessor :platform

    # Ordering platform ID in use by a Cookies store (public).
    # @return [String]
    attr_accessor :store_id

    # Whether online ordering is enabled for a given Cookies store.
    # @return [Boolean]
    attr_accessor :enabled

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['platform'] = 'platform'
      @_hash['store_id'] = 'storeId'
      @_hash['enabled'] = 'enabled'
      @_hash
    end

    # An array for optional fields
    def optionals
      []
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(platform = nil,
                   store_id = nil,
                   enabled = nil)
      @platform = platform unless platform == SKIP
      @store_id = store_id unless store_id == SKIP
      @enabled = enabled unless enabled == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      platform = hash.key?('platform') ? hash['platform'] : SKIP
      store_id = hash.key?('storeId') ? hash['storeId'] : SKIP
      enabled = hash.key?('enabled') ? hash['enabled'] : SKIP

      # Create object from extracted values.
      StoreOrdering.new(platform,
                        store_id,
                        enabled)
    end
  end
end
