# cookies_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CookiesApi
  # Branding information for a physical retail store.
  class StoreBranding < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Specifies the first-party brand for a store.
    # @return [FirstPartyBranding]
    attr_accessor :first_party

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['first_party'] = 'firstParty'
      @_hash
    end

    # An array for optional fields
    def optionals
      []
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(first_party = nil)
      @first_party = first_party unless first_party == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      first_party = FirstPartyBranding.from_hash(hash['firstParty']) if hash['firstParty']

      # Create object from extracted values.
      StoreBranding.new(first_party)
    end
  end
end
