# cookies_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CookiesApi
  # Specifies a place in time in relative terms to the start of a given day.
  class TimeSpec < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Hours value for this time specification.
    # @return [Integer]
    attr_accessor :hours

    # Minutes value for this time specification.
    # @return [String]
    attr_accessor :minutes

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['hours'] = 'hours'
      @_hash['minutes'] = 'minutes'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        minutes
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(hours = nil,
                   minutes = nil)
      @hours = hours unless hours == SKIP
      @minutes = minutes unless minutes == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      hours = hash.key?('hours') ? hash['hours'] : SKIP
      minutes = hash.key?('minutes') ? hash['minutes'] : SKIP

      # Create object from extracted values.
      TimeSpec.new(hours,
                   minutes)
    end
  end
end
