# cookies_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CookiesApi
  #  cookies_api client class.
  class Client
    attr_reader :config

    # Access to stores controller.
    # @return [StoresController] Returns the controller instance.
    def stores
      @stores ||= StoresController.new config
    end

    # Access to strains controller.
    # @return [StrainsController] Returns the controller instance.
    def strains
      @strains ||= StrainsController.new config
    end

    # Access to brands controller.
    # @return [BrandsController] Returns the controller instance.
    def brands
      @brands ||= BrandsController.new config
    end

    def initialize(timeout: 60, max_retries: 0, retry_interval: 1,
                   backoff_factor: 2,
                   retry_statuses: [408, 413, 429, 500, 502, 503, 504, 521, 522, 524],
                   retry_methods: %i[get put],
                   environment: Environment::SANDBOX, x_apikey: '', apikey: '',
                   config: nil)
      @config = if config.nil?
                  Configuration.new(timeout: timeout, max_retries: max_retries,
                                    retry_interval: retry_interval,
                                    backoff_factor: backoff_factor,
                                    retry_statuses: retry_statuses,
                                    retry_methods: retry_methods,
                                    environment: environment,
                                    x_apikey: x_apikey, apikey: apikey)
                else
                  config
                end
    end
  end
end
